# fly.toml app configuration file generated for google-project on 2024-08-04T17:49:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'google-project'
primary_region = 'sin'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '7860'
  GOOGLE_API_KEY = 'AIzaSyAME6hNA81PSYx1ThPbNc8UKnNJQfovBSU'
  UPSTAGE_API_KEY = 'up_ps3sghU2P7szwsVZHshLvuXmmtxEw'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 2
